<?xml version="1.0"?>
<!DOCTYPE jx:template [
        <!ELEMENT jx:template (jx:import|jx:macro)*>
        <!ATTLIST jx:template
                xmlns:jx CDATA #REQUIRED
                xmlns:ft CDATA #REQUIRED
                xmlns:fi CDATA #REQUIRED
                xmlns:i18n CDATA #REQUIRED>
        <!ELEMENT jx:import (#PCDATA)>
        <!ATTLIST jx:import
                uri CDATA #REQUIRED>
        <!ELEMENT jx:macro (jx:parameter|jx:set|jx:choose|jx:if|ft:group|div|script|ft:widget|ul|userData|parents|tags|ft:repeater|link)*>
        <!ATTLIST jx:macro
                name CDATA #REQUIRED
                targetNamespace CDATA #IMPLIED>
        <!ELEMENT jx:parameter (#PCDATA)>
        <!ATTLIST jx:parameter
                default CDATA #IMPLIED
                name CDATA #REQUIRED>
        <!ELEMENT jx:set (#PCDATA)>
        <!ATTLIST jx:set
                value CDATA #REQUIRED
                var CDATA #REQUIRED>
        <!ELEMENT jx:choose (jx:when|jx:otherwise)*>
        <!ELEMENT jx:when (jx:set|a|systemURL|br|em)*>
        <!ATTLIST jx:when
                test CDATA #REQUIRED>
        <!ELEMENT jx:otherwise (jx:set|i18n:text|justName|ft:repeater-rows)*>
        <!ELEMENT jx:if (jx:set|jx:evalBody|li|script|div)*>
        <!ATTLIST jx:if
                test CDATA #REQUIRED>
        <!ELEMENT jx:evalBody (#PCDATA)>
        <!ELEMENT ft:group (li)*>
        <!ATTLIST ft:group
                id CDATA #REQUIRED>
        <!ELEMENT li (label|ft:widget|span|jx:set|script|ft:repeater)*>
        <!ATTLIST li
                class CDATA #IMPLIED>
        <!ELEMENT label (ft:widget-label|i18n:text)*>
        <!ATTLIST label
                class CDATA #REQUIRED
                for CDATA #REQUIRED
                title CDATA #IMPLIED>
        <!ELEMENT ft:widget-label (#PCDATA)>
        <!ATTLIST ft:widget-label
                id CDATA #REQUIRED>
        <!ELEMENT ft:widget (fi:styling|fi:selection-list)*>
        <!ATTLIST ft:widget
                id CDATA #REQUIRED>
        <!ELEMENT fi:styling (#PCDATA)>
        <!ATTLIST fi:styling
                class CDATA #IMPLIED
                cols CDATA #IMPLIED
                name CDATA #IMPLIED
                onChange CDATA #IMPLIED
                role CDATA #IMPLIED
                rows CDATA #IMPLIED
                size CDATA #IMPLIED
                style CDATA #IMPLIED
                title CDATA #IMPLIED
                type CDATA #IMPLIED>
        <!ELEMENT div (div|span|a|jx:attribute|ft:widget|ul|label)*>
        <!ATTLIST div
                class CDATA #IMPLIED
                i18n:attr CDATA #IMPLIED
                id CDATA #IMPLIED
                name CDATA #IMPLIED
                title CDATA #IMPLIED>
        <!ELEMENT script (i18n:text|jx:forEach)*>
        <!ATTLIST script
                src CDATA #IMPLIED
                type CDATA #REQUIRED>
        <!ELEMENT fi:selection-list (jx:forEach)*>
        <!ELEMENT jx:forEach (fi:item|parent)*>
        <!ATTLIST jx:forEach
                items CDATA #REQUIRED
                var CDATA #REQUIRED
                varStatus CDATA #IMPLIED>
        <!ELEMENT fi:item (fi:label)*>
        <!ATTLIST fi:item
                value CDATA #REQUIRED>
        <!ELEMENT fi:label (#PCDATA)>
        <!ELEMENT ul (jx:if|jx:choose|lables|objectRows|li|ft:repeater-rows)*>
        <!ATTLIST ul
                class CDATA #REQUIRED
                id CDATA #IMPLIED>
        <!ELEMENT i18n:text (#PCDATA)>
        <!ATTLIST i18n:text
                key CDATA #REQUIRED>
        <!ELEMENT span (jx:choose|input|ft:widget|a)*>
        <!ATTLIST span
                align CDATA #IMPLIED
                class CDATA #IMPLIED
                dir CDATA #IMPLIED
                id CDATA #IMPLIED
                width CDATA #IMPLIED>
        <!ELEMENT a (jx:attribute)*>
        <!ATTLIST a
                class CDATA #IMPLIED
                href CDATA #IMPLIED
                id CDATA #IMPLIED>
        <!ELEMENT input (#PCDATA)>
        <!ATTLIST input
                type CDATA #REQUIRED
                i18n:attr CDATA #REQUIRED
                value CDATA #REQUIRED
                onclick CDATA #REQUIRED>
        <!ELEMENT systemURL (#PCDATA)>
        <!ELEMENT justName (#PCDATA)>
        <!ELEMENT lables (#PCDATA)>
        <!ELEMENT objectRows (#PCDATA)>
        <!ELEMENT userData (#PCDATA)>
        <!ATTLIST userData
                name CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT parents (jx:forEach)*>
        <!ELEMENT parent (name)*>
        <!ATTLIST parent
                id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT tags (#PCDATA)>
        <!ELEMENT ft:repeater (ft:repeater-rows|div|jx:choose|table)*>
        <!ATTLIST ft:repeater
                id CDATA #REQUIRED>
        <!ELEMENT ft:repeater-rows (jx:set|div|li|tr)*>
        <!ELEMENT jx:attribute (jx:choose)*>
        <!ATTLIST jx:attribute
                name CDATA #REQUIRED>
        <!ELEMENT link (#PCDATA)>
        <!ATTLIST link
                href CDATA #REQUIRED
                media CDATA #REQUIRED
                rel CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT br (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT table (tbody)*>
        <!ATTLIST table
                border CDATA #REQUIRED
                class CDATA #REQUIRED>
        <!ELEMENT tbody (ft:repeater-rows)*>
        <!ELEMENT tr (td)*>
        <!ATTLIST tr
                class CDATA #REQUIRED>
        <!ELEMENT td (jx:set|span|ft:widget)*>
        ]>
<jx:template xmlns:jx="http://apache.org/cocoon/templates/jx/1.0"
             xmlns:ft="http://apache.org/cocoon/forms/1.0#template"
             xmlns:fi="http://apache.org/cocoon/forms/1.0#instance"
             xmlns:i18n="http://apache.org/cocoon/i18n/2.1">

    <jx:import uri="servlet:forms:/resource/internal/generation/jx-macros.xml"/>

    <jx:macro name="form-template" targetNamespace="http://apache.org/cocoon/forms/1.0#template">
        <jx:parameter name="location"/>

        <jx:set var="localeSitemapParameter" value="${cocoon.parameters.getParameter('locale', '')}"/>
        <jx:set var="cformsHelper"
                value="#{org.apache.cocoon.forms.generation.JXMacrosHelper.createHelper($cocoon/consumer,$cocoon/request,$localeSitemapParameter)}"/>
        <jx:set var="attributeName" value="${cocoon.parameters['attribute-name']}"/>
        <jx:choose>
            <jx:when test="${attributeName and attributeName.length() > 0}">
                <jx:set var="form" value="${cformsHelper.getForm(null, attributeName)}"/>
            </jx:when>
            <jx:when test="${location}">
                <jx:set var="var" value="${macro.arguments.remove('location')}"/>
                <jx:set var="form" value="${cformsHelper.getForm(location, attributeName)}"/>
            </jx:when>
            <jx:otherwise>
                <jx:set var="form" value="${cformsHelper.getForm(CocoonFormsInstance, attributeName)}"/>
            </jx:otherwise>
        </jx:choose>

        <jx:if test="${form != null and cformsHelper.isVisible(form)}">
            <jx:set var="cformsDummy" value="${cformsHelper.startForm(form, macro.arguments)}"/>
            <!--  the form is also the current widget
            -->
            <jx:set var="widget" value="${form}"/>
            <jx:evalBody/>
            <jx:set var="cformsDummy" value="${cformsHelper.endForm()}"/>
        </jx:if>
    </jx:macro>


    <jx:macro name="justName">
        <ft:group id="justName">
            <li>
                <label title="name" for="name" class="label">
                    <ft:widget-label id="name"/>
                </label>
                <ft:widget id="name">
                    <fi:styling size="50"/>
                </ft:widget>

            </li>
        </ft:group>
    </jx:macro>

    <jx:macro name="systemURL">
        <ft:group id="systemURL">
            <li>
                <label title="name" for="name" class="label">
                    <ft:widget-label id="name"/>
                </label>
                <ft:widget id="name">
                    <fi:styling size="50"/>
                </ft:widget>
                <!--<ft:widget id="id">
                    <fi:styling type="hidden"/>
                </ft:widget>-->
            </li>
            <li>
                <label for="systemName" class="label">
                    <ft:widget-label id="systemName"/>
                </label>
                <ft:widget id="systemName">
                    <fi:styling size="45"/>
                </ft:widget>

                <ft:widget id="checkSystemName"/>

            </li>
        </ft:group>
    </jx:macro>
    <jx:macro name="translate">

        <div class="punto"/>
        <script type="text/javascript">
            function changeLocale(languageCode){
            $("div.meta-info").hide();
            var targetDivName ='translate_'+languageCode;
            '*[name= targetDivName]'
            $('*[name='+ targetDivName+']').show();
            <!--var newFormLocale = document.getElementById('translate');-->
            var newFormLocale = document.getElementById('formLocale');
            newFormLocale.value = languageCode;

            if(document.getElementById('documentForm') != null){
            submitAll(languageCode);
            }else{
            cocoon.forms.submitForm(newFormLocale);
            }
            <!--if(cocoon.session.getAttribute("languageCode")){

            }-->

            <!--cocoon.forms.submitForm(dynamicForm);-->

            <!--var dynamicForm = document.getElementById('dynamicForm');-->
            <!--submit DocType-->
            var documentTypeForm =document.getElementById('dynamicForm');
            if(documentTypeForm != null){
            <!--cocoon.forms.submitForm(documentTypeForm);-->
            <!--cocoon.forms.submitForm(contentForm);-->
            <!--cocoon.forms.submitForm(documentTypeForm);-->
            <!--cocoon.forms.submitForm(all);-->
            }
            }
        </script>

        <ft:widget id="translate">
            <!--<fi:styling class="chzn-select" style="width:350px;" onChange="changeLocale(this.value);"/>-->
            <fi:styling class="chzn-select" style="width:350px;" onChange="changeLocale(this.value);"/>
            <fi:selection-list>

                <jx:forEach items="${availableLanguages}" var="language">
                    <fi:item value="${language.code}">
                        <fi:label>${language.name}</fi:label>
                    </fi:item>
                </jx:forEach>
            </fi:selection-list>
        </ft:widget>

        <script type="text/javascript">
            $(".chzn-select").chosen();
        </script>
        <ft:widget id="formLocale">
            <fi:styling type="hidden"/>
        </ft:widget>

    </jx:macro>
    <jx:macro name="emsFields">
        <jx:parameter name="entity"/>
        <jx:parameter name="id"/>
        <jx:parameter name="parentId" default="0"/>
        <jx:parameter name="parentName" default=""/>
        <jx:parameter name="showParents" default="0"/>
        <jx:set var="attributeName" value="${cocoon.parameters['attribute-name']}"/>
        <ul class="simple-list">
            <jx:if test="${showParents == 1}">
                <li>
                    <label title="" for="parentName" class="label">
                        <i18n:text key="EmsObject.parentElement"/>
                    </label>

                    <span id="parentName">
                        <jx:choose>
                            <jx:when test="${parentId > 0}">
                                <a href="${entity}-edit?id=${parentId}">${parentName}</a>
                            </jx:when>
                            <jx:otherwise>
                                <i18n:text key="EmsObject.noParentElement"/>
                            </jx:otherwise>
                        </jx:choose>
                    </span>
                    <!--<h1>ID:${id}</h1>-->
                    <span align="right" width="300px">
                        <input type="button" i18n:attr="value" value="Modify" onclick="openParentDialog(${id})"/>
                        <ft:widget id="parentId">
                            <fi:styling type="hidden"/>
                        </ft:widget>
                    </span>
                </li>

                <script type="text/javascript">
                    var noParentLabel = '!<i18n:text key="EmsObject.noParentElement"/>';

                    function openParentDialog(thisId) {
                    $("#parentTreeContainer:ui-dialog").dialog("destroy");
                    $("#parentTreeContainer").dialog({
                    width: 800,
                    height:400,
                    modal: true,
                    buttons: {
                    "<i18n:text key="Save"/>": function() {
                    $(this).dialog("close");
                    }
                    }
                    });


                    var divId = "#parentTree";
                    var entity = "${entity}";
                    if (entity =='FileObject'){
                    entity ='Folder'
                    }
                    var ajaxUrl;
                    if(thisId > 0){
                    ajaxUrl = "/ems/core/treeObjects?entity="+entity+"&amp;excludedId="+thisId;
                    }
                    else{
                    ajaxUrl = "/ems/core/treeObjects?entity="+entity;
                    }


                    document.getElementById('parentTreeRootNode').value=0;
                    document.getElementById('parentTreeRootNode').innerHTML=entity;
                    initXmlTree(divId, ajaxUrl);

                    $("#parentTreeRootNode").click( function () {
                    updateParentData(noParentLabel,0);
                    });
                    $("#parentTree").click(function (e) {
                    var f = jQuery.jstree._focused();
                    var id = f.data.ui.selected.attr("id");
                    var name = f.data.ui.selected.attr("name");
                    updateParentData(name,id);
                    });

                    function updateParentData(name,id){

                    document.getElementById('parentId').value = id;
                    document.getElementById('parentName').innerHTML =name;
                    cocoon.forms.submitForm(document.getElementById('parentId'));
                    };
                    };

                </script>

                <div i18n:attr="title" title="core:Content.choose" id="parentTreeContainer" class="dialogContent">
                    <div class="common-div">
                        <span class="ui-icon-home"/>
                        <a id="parentTreeRootNode" href="#" class="">HOME</a>
                    </div>
                    <div id="parentTree"/>
                </div>

            </jx:if>
            <jx:choose>
                <jx:when test="${showParents == 1}">
                    <systemURL/>
                </jx:when>
                <jx:otherwise>
                    <justName/>
                </jx:otherwise>
            </jx:choose>
            <lables/>

            <objectRows/>
        </ul>


    </jx:macro>

    <jx:macro name="userDataMacro">
        <userData name="${userData.name}" id="${userData.id}"/>
    </jx:macro>


    <jx:macro name="parentObjects">
        <parents>
            <jx:forEach items="${parents}" var="parent" varStatus="status">
                <parent id="${parent.id}">
                    <name>${parent.name}</name>
                </parent>
            </jx:forEach>
        </parents>
    </jx:macro>



    <jx:macro name="lables">
        <!--<a href="#" id="labelsLink2" i18n:attr="title" title="ems:common.labels"
           onclick="hideLabelsDialog()">
            <i18n:text catalogue="ems" key="common.close"/>CLOSE
        </a>-->
        <ft:repeater id="labels">
            <!--<jx:if test="${actionState == 'create'}">
                <div style="display:none">
            </jx:if>-->
            <!-- <script type="text/javascript">

                jQuery(function() {
                &lt;!&ndash;accodrion &ndash;&gt;
                jQuery( "#accordion-translation" ).accordion({autoHeight: false,
                navigation: true});
                });
            </script>-->
            <!--<div id="accordion-translation">-->
            <!--class="widget-black"-->
            <jx:choose>
                <jx:when test="${repeater.getSize() == 0}">
                    <br/>
                    <em>LABLES: There is no data to display</em>
                </jx:when>
                <jx:otherwise>
                    <ft:repeater-rows>
                        <jx:set var="rowLanguageCode"
                                value="${repeater.getRow(repeaterLoop.index).getChild('languageCode').value}"/>
                        <!--<ft:group id="metaInfo">-->
                        <!--      <h3 position="${repeaterLoop.index % 2}" style="padding-left:30px">
                            ${widget.lookupWidget('languageCode').value} :
                            ${widget.lookupWidget('languageName').value}
                        </h3>-->
                        <!--forms-row-${repeaterLoop.index % 2}-->
                        <div class="meta-info" name="translate_${rowLanguageCode}">
                            <jx:attribute name="style">
                                <jx:choose>
                                    <!--<jx:when test="${rowLanguageCode == formLocale}">-->
                                    <jx:when test="${rowLanguageCode == languageCode}">
                                        display:block;
                                    </jx:when>
                                    <jx:otherwise>
                                        display:none;
                                    </jx:otherwise>
                                </jx:choose>
                            </jx:attribute>

                            <!--<ft:widget id="id">
                                <fi:styling type="hidden"/>
                            </ft:widget>-->
                            <ft:widget id="languageCode">
                                <fi:styling type="hidden"/>
                            </ft:widget>
                            <ft:widget id="objectId">
                                <fi:styling type="hidden"/>
                            </ft:widget>
                            <label for="label" class="label">
                                <ft:widget-label id="label"/>

                            </label>
                            <ft:widget id="label">
                                <fi:styling size="50" style="font-size:23px;"/>
                            </ft:widget>

                        </div>
                    </ft:repeater-rows>

                </jx:otherwise>
            </jx:choose>
            <!--</div>-->
        </ft:repeater>
    </jx:macro>

    <jx:macro name="linked">
        <ft:repeater id="linked">
            <table border="0" class="order">
                <tbody>
                    <ft:repeater-rows>
                        <tr class="forms-row">
                            <td>
                                <jx:set var="linkId"
                                        value="${repeater.getRow(repeaterLoop.index).getChild('id').value}"/>

                                <jx:set var="linkName"
                                        value="${repeater.getRow(repeaterLoop.index).getChild('name').value}"/>
                                <jx:set var="linkDate"
                                        value="${repeater.getRow(repeaterLoop.index).getChild('publishDateTime').value}"/>
                                <!--<ft:widget id="id"/>-->
                            </td>
                            <td>
                                <span class="label">
                                    <a>
                                        <jx:attribute name="href">/ems/core/Content-edit?id=${linkId}</jx:attribute>
                                        ${linkName}
                                    </a>
                                </span>
                            </td>
                            <td>
                                <span class="label">
                                    ${linkDate}
                                </span>
                            </td>
                            <td>
                                <ft:widget id="delete">
                                    <fi:styling type="link" role="button"
                                                class="ui-button ui-corner-all ui-icon ui-icon-closethick"/>
                                </ft:widget>
                            </td>
                        </tr>
                    </ft:repeater-rows>
                </tbody>
            </table>
        </ft:repeater>


    </jx:macro>

</jx:template>